name: Build Project

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
        
permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Download SCP:SL References
        uses: Axwabo/scpsl-references-downloader@v1
        id: refs

      - name: Install tools
        run: dotnet tool install -g dotnet-t4

      - name: Build
        run: dotnet build -c:Release -o Out
        env:
          ReferencePath: ${{ steps.refs.outputs.target }}

      - name : Upload
        uses: actions/upload-artifact@v7
        with:
          name: Project
          path: Out/*

  release:
    name: Release Dev build
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts
          
      - name: Delete old release
        env:
          GITHUB_TOKEN: ${{ secrets.gh_token }}
        run: |
          gh release delete latest --cleanup-tag -y || true

      - uses: softprops/action-gh-release@v3
        with:
          token: "${{ secrets.gh_token }}"
          tag_name: "latest"
          prerelease: true
          name: "Development Build"
          files: |
            artifacts/**
