name: Build Project

on:
  workflow_call:
    secrets:
      gh_token:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Download SCP:SL References
        uses: Axwabo/scpsl-references-downloader@v1
        id: refs

      - name: Install tools
        run: dotnet tool install dotnet-t4

      - name: Build
        run: dotnet build -c:Release -o Out
        env:
          ReferencePath: ${{ steps.refs.outputs.target }}

      - name : Upload
        uses: actions/upload-artifact@v7
        with:
          name: Project
          path: Out/*

  release:
    name: Release Dev build
    if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Variables
        id: vars
        run: echo sha_short=${GITHUB_SHA::7} >> $GITHUB_OUTPUT
        
      - uses: actions/download-artifact@v8
        with:
          path: artifacts

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.gh_token }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            artifacts/**
