name: Dependency Update

on:
  workflow_call:
    inputs:
      dependencies:
        description: 'JSON array of dependencies (repo, version)'
        required: true
        type: string
    secrets:
      gh_token:
        required: true


jobs:
  dependency-update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
    
      - name: Download releases using GitHub CLI
        run: |
          mkdir -p "3rdparty"
          echo "Login with token..."
          echo "${{ secrets.gh_token }}" | gh auth login --with-token
          echo "Starting downloads..."
          
          echo '${{ inputs.dependencies }}' | jq -c '.[]' | while read -r item; do
            
            repo=$(echo "$item" | jq -r '.repo')
            version=$(echo "$item" | jq -r '.version')
            
            echo "----------------------------------------"
            echo "Fetching: $repo | Tag: $version"
            
            # Download the asset
            gh release download "$version" \
              --repo "$repo" \
              --dir 3rdparty --clobber
              
          done

          echo "Download finished!"

      - name: Upload dependencies as artifact
        uses: actions/upload-artifact@v7
        with:
          name: 3rdparty
          path: "3rdparty/**"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Update 3rdparty
          title: Update 3rdparty
          body: Update 3rdparty dependency
          branch: auto/update-3rdparty
          branch-suffix: short-commit-hash
