name: Dependency Update

on:
  workflow_call:
    inputs:
      dependencies:
        description: 'JSON array of dependencies (repo, version)'
        required: true
        type: string
      folder:
        description: 'The name of the folder to download dependencies to.'
        required: false
        type: string
        default: '3rdparty'
      name:
        description: 'The name of the artifact.'
        required: false
        type: string
        default: '3rdparty'
    secrets:
      gh_token:
        required: true


jobs:
  dependency-update:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
    
      - name: Download releases using GitHub CLI
        continue-on-error: true
        run: |
          mkdir -p "${{ inputs.folder }}"
          echo "Login with token..."
          echo "${{ secrets.gh_token }}" | gh auth login --with-token
          echo "Starting downloads..."
          
          echo '${{ inputs.dependencies }}' | jq -c '.[]' | while read -r item; do
            
            repo=$(echo "$item" | jq -r '.repo')
            version=$(echo "$item" | jq -r '.version')
            
            echo "----------------------------------------"
            echo "Fetching: $repo | Tag: $version"
            
            # Download the asset
            gh release download "$version" \
              --repo "$repo" \
              --dir "${{ inputs.folder }}" --clobber
              
          done

          echo "Download finished!"

      - name: Upload dependencies as artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.name }}
          path: "${{ inputs.folder }}/**"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: Update ${{ inputs.name }}
          title: Update ${{ inputs.name }}
          body: Update ${{ inputs.name }}
          branch: auto/update-${{ inputs.name }}
          branch-suffix: short-commit-hash
